In [ ]:
# ============================================================
# GENERIC CSV DATASET PROFILER - GOOGLE COLAB VERSION
# ============================================================

import pandas as pd
import numpy as np
from google.colab import files
import io


# ------------------------------------------------------------
# 1. Upload CSV file
# ------------------------------------------------------------

print("Please upload your CSV dataset:")

uploaded = files.upload()

# Get uploaded file name automatically
file_name = next(iter(uploaded))

print("\nUploaded file:", file_name)


# ------------------------------------------------------------
# 2. Load dataset
# ------------------------------------------------------------

try:
    df = pd.read_csv(io.BytesIO(uploaded[file_name]))

except UnicodeDecodeError:
    # Try another common encoding
    df = pd.read_csv(
        io.BytesIO(uploaded[file_name]),
        encoding="latin1"
    )

print("\nDataset loaded successfully!")


# ------------------------------------------------------------
# 3. Basic Dataset Information
# ------------------------------------------------------------

print("\n========== DATASET PROFILE ==========\n")

print("File Name:")
print(file_name)

print("\nDataset Shape:")
print("Rows   :", df.shape[0])
print("Columns:", df.shape[1])


# ------------------------------------------------------------
# 4. Column Names
# ------------------------------------------------------------

print("\n========== COLUMN NAMES ==========\n")

for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")


# ------------------------------------------------------------
# 5. Data Types
# ------------------------------------------------------------

print("\n========== DATA TYPES ==========\n")

print(df.dtypes)


# ------------------------------------------------------------
# 6. First 5 Rows
# ------------------------------------------------------------

print("\n========== FIRST 5 ROWS ==========\n")

print(df.head())


# ------------------------------------------------------------
# 7. Missing Values
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========\n")

missing_values = df.isnull().sum()

missing_percentage = (
    df.isnull().sum() / len(df) * 100
).round(2)

missing_report = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage (%)": missing_percentage
})

print(missing_report)


# ------------------------------------------------------------
# 8. Duplicate Rows
# ------------------------------------------------------------

print("\n========== DUPLICATE ROWS ==========\n")

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)


# ------------------------------------------------------------
# 9. Unique Values
# ------------------------------------------------------------

print("\n========== UNIQUE VALUES ==========\n")

unique_values = df.nunique()

print(unique_values)


# ------------------------------------------------------------
# 10. Numerical Column Statistics
# ------------------------------------------------------------

print("\n========== NUMERICAL STATISTICS ==========\n")

numeric_columns = df.select_dtypes(
    include=np.number
).columns

if len(numeric_columns) > 0:
    print(df[numeric_columns].describe())
else:
    print("No numerical columns found.")


# ------------------------------------------------------------
# 11. Categorical Column Statistics
# ------------------------------------------------------------

print("\n========== CATEGORICAL STATISTICS ==========\n")

categorical_columns = df.select_dtypes(
    include=["object", "category"]
).columns

if len(categorical_columns) > 0:
    print(df[categorical_columns].describe())
else:
    print("No categorical columns found.")


# ------------------------------------------------------------
# 12. Detailed Column Profile
# ------------------------------------------------------------

print("\n========== DETAILED COLUMN PROFILE ==========\n")

profile_data = []

for column in df.columns:

    total_values = len(df[column])

    missing = df[column].isnull().sum()

    unique = df[column].nunique()

    dtype = str(df[column].dtype)

    profile_data.append({
        "Column Name": column,
        "Data Type": dtype,
        "Total Values": total_values,
        "Missing Values": missing,
        "Missing %": round(
            (missing / total_values) * 100, 2
        ) if total_values > 0 else 0,
        "Unique Values": unique
    })


profile_df = pd.DataFrame(profile_data)

print(profile_df)


# ------------------------------------------------------------
# 13. Memory Usage
# ------------------------------------------------------------

print("\n========== MEMORY USAGE ==========\n")

memory_usage = df.memory_usage(deep=True).sum()

print(
    "Total Memory Usage:",
    round(memory_usage / 1024, 2),
    "KB"
)


# ------------------------------------------------------------
# 14. Save Dataset Profile to CSV
# ------------------------------------------------------------

output_file = "dataset_profile.csv"

profile_df.to_csv(
    output_file,
    index=False
)

print("\nDataset profile saved as:", output_file)


# ------------------------------------------------------------
# 15. Download Profile
# ------------------------------------------------------------

files.download(output_file)


print("\n========== PROFILING COMPLETED ==========")

Please upload your CSV dataset:

Saving 2020_al_data_kaggle_upload_new_old_syllabi.csv to 2020_al_data_kaggle_upload_new_old_syllabi.csv

Uploaded file: 2020_al_data_kaggle_upload_new_old_syllabi.csv

Dataset loaded successfully!

========== DATASET PROFILE ==========

File Name:
2020_al_data_kaggle_upload_new_old_syllabi.csv

Dataset Shape:
Rows   : 337553
Columns: 19

========== COLUMN NAMES ==========

1. index
2. stream
3. Zscore
4. district_rank
5. island_rank
6. al_year
7. sub1
8. sub1_r
9. sub2
10. sub2_r
11. sub3
12. sub3_r
13. cgt_r
14. ge_r
15. syllabus
16. birth_day
17. birth_month
18. birth_year
19. gender

========== DATA TYPES ==========

index             int64
stream           object
Zscore           object
district_rank    object
island_rank      object
al_year           int64
sub1             object
sub1_r           object
sub2             object
sub2_r           object
sub3             object
sub3_r           object
cgt_r            object
ge_r             object
syllabus         object
birth_day        object
birth_month      object
birth_year       object
gender           object
dtype: object

========== FIRST 5 ROWS ==========

   index    stream  Zscore district_rank  island_rank  al_year  \
0      0      ARTS  -.3550    4336 (NEW)  64994 (NEW)     2020
1      1      ARTS  -.2648    4154 (NEW)  62338 (NEW)     2020
2      2  COMMERCE  -.4760    6910 (NEW)  37307 (NEW)     2020
3      3  COMMERCE  -.1012    5678 (NEW)  30449 (NEW)     2020
4      4  COMMERCE   .6014    3269 (NEW)  17010 (NEW)     2020

                sub1 sub1_r               sub2 sub2_r        sub3 sub3_r  \
0  POLITICAL SCIENCE      S  DANCING(BHARATHA)      C       TAMIL      S
1  POLITICAL SCIENCE      S     CARNATIC MUSIC      C       TAMIL      C
2          ECONOMICS      S   BUSINESS STUDIES      S  ACCOUNTING      S
3          ECONOMICS      C   BUSINESS STUDIES      C  ACCOUNTING      S
4          ECONOMICS      C   BUSINESS STUDIES      C  ACCOUNTING      B

  cgt_r ge_r syllabus birth_day birth_month birth_year  gender
0   056    S      new        31         May       2001  female
1   032    C      new        13     January       2002  female
2   050    S      new        16      August       2001  female
3   034    S      new        16      August       2001  female
4   036    S      new         7      August       2000  female

========== MISSING VALUES ==========

               Missing Values  Missing Percentage (%)
index                       0                    0.00
stream                      0                    0.00
Zscore                      0                    0.00
district_rank               0                    0.00
island_rank                 0                    0.00
al_year                     0                    0.00
sub1                        0                    0.00
sub1_r                      0                    0.00
sub2                        0                    0.00
sub2_r                      0                    0.00
sub3                        0                    0.00
sub3_r                      0                    0.00
cgt_r                       0                    0.00
ge_r                        0                    0.00
syllabus                    0                    0.00
birth_day                   0                    0.00
birth_month                 0                    0.00
birth_year                  0                    0.00
gender                   1484                    0.44

========== DUPLICATE ROWS ==========

Number of duplicate rows: 0

========== UNIQUE VALUES ==========

index            337553
stream                8
Zscore            33891
district_rank      8060
island_rank       47616
al_year               1
sub1                 51
sub1_r                7
sub2                 60
sub2_r                7
sub3                 60
sub3_r                8
cgt_r                73
ge_r                  7
syllabus              2
birth_day            34
birth_month          15
birth_year           76
gender                3
dtype: int64

========== NUMERICAL STATISTICS ==========

               index   al_year
count  337553.000000  337553.0
mean   168776.000000    2020.0
std     97443.302045       0.0
min         0.000000    2020.0
25%     84388.000000    2020.0
50%    168776.000000    2020.0
75%    253164.000000    2020.0
max    337552.000000    2020.0

========== CATEGORICAL STATISTICS ==========

        stream  Zscore district_rank island_rank     sub1  sub1_r       sub2  \
count   337553  337553        337553      337553   337553  337553     337553
unique       8   33891          8060       47616       51       7         60
top          -       -             -           -  PHYSICS       S  CHEMISTRY
freq    150514  105249        153254      153254    88758   97338      83993

        sub2_r     sub3  sub3_r   cgt_r    ge_r syllabus birth_day  \
count   337553   337553  337553  337553  337553   337553    337553
unique       7       60       8      73       7        2        34
top          S  SINHALA       S  Absent       F      new         1
freq     89408    75708   88383   76628  123804   306211     11297

       birth_month birth_year  gender
count       337553     337553  336069
unique          15         76       3
top            May       2001  female
freq         29424     185402  193326

========== DETAILED COLUMN PROFILE ==========

      Column Name Data Type  Total Values  Missing Values  Missing %  \
0           index     int64        337553               0       0.00
1          stream    object        337553               0       0.00
2          Zscore    object        337553               0       0.00
3   district_rank    object        337553               0       0.00
4     island_rank    object        337553               0       0.00
5         al_year     int64        337553               0       0.00
6            sub1    object        337553               0       0.00
7          sub1_r    object        337553               0       0.00
8            sub2    object        337553               0       0.00
9          sub2_r    object        337553               0       0.00
10           sub3    object        337553               0       0.00
11         sub3_r    object        337553               0       0.00
12          cgt_r    object        337553               0       0.00
13           ge_r    object        337553               0       0.00
14       syllabus    object        337553               0       0.00
15      birth_day    object        337553               0       0.00
16    birth_month    object        337553               0       0.00
17     birth_year    object        337553               0       0.00
18         gender    object        337553            1484       0.44

    Unique Values
0          337553
1               8
2           33891
3            8060
4           47616
5               1
6              51
7               7
8              60
9               7
10             60
11              8
12             73
13              7
14              2
15             34
16             15
17             76
18              3

========== MEMORY USAGE ==========

Total Memory Usage: 311363.91 KB

Dataset profile saved as: dataset_profile.csv

========== PROFILING COMPLETED ==========

### Students with Z-score > 0.5 in BIOLOGICAL SCIENCE Stream

In [ ]:
# Filter for 'BIOLOGICAL SCIENCE' stream and Zscore > 0.4
biological_science_high_zscore_students = df_cleaned[
    (df_cleaned['stream'] == 'BIOLOGICAL SCIENCE') &
    (df_cleaned['Zscore'] > 0.4)
]

# Display the results
print(f"Number of students in 'BIOLOGICAL SCIENCE' stream with Z-score > 0.4: {len(biological_science_high_zscore_students)}")
display(biological_science_high_zscore_students.head())

Number of students in 'BIOLOGICAL SCIENCE' stream with Z-score > 0.4: 14163

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender
221,221,BIOLOGICAL SCIENCE,0.8301,1401 (NEW),7642 (NEW),2020,PHYSICS,S,CHEMISTRY,C,BIOLOGY,C,066,A,new,16,July,2001,male
268,268,BIOLOGICAL SCIENCE,1.3942,761 (NEW),3551 (NEW),2020,PHYSICS,B,CHEMISTRY,B,BIOLOGY,C,068,A,new,21,October,2001,male
293,293,BIOLOGICAL SCIENCE,2.4107,57 (NEW),211 (NEW),2020,PHYSICS,A,CHEMISTRY,A,BIOLOGY,B,060,B,new,26,July,2001,male
362,362,BIOLOGICAL SCIENCE,1.1235,1050 (NEW),5268 (NEW),2020,PHYSICS,C,CHEMISTRY,B,BIOLOGY,C,070,A,new,26,January,2001,male
367,367,BIOLOGICAL SCIENCE,1.1875,971 (NEW),4809 (NEW),2020,PHYSICS,C,CHEMISTRY,C,BIOLOGY,A,Absent,Absent,new,9,October,2000,male

### Save to CSV and Download

In [ ]:
# Define the output CSV file name
output_csv_file = 'biological_science_high_zscore_students.csv'

# Save the filtered DataFrame to a CSV file
biological_science_high_zscore_students.to_csv(output_csv_file, index=False)

print(f"Data saved to {output_csv_file}")

# Provide a download link
files.download(output_csv_file)

Data saved to biological_science_high_zscore_students.csv

### Removing Null Values from `biological_science_high_zscore_students`

In [ ]:
import pandas as pd
import io
from google.colab import files # Required for file operations if needed

# Check if 'df' is already defined. If not, try to reload it.
# This makes the cell more robust against kernel restarts.
if 'df' not in locals():
    print("DataFrame 'df' not found, attempting to reload from original CSV.")
    # Assuming the original file name is known and the file exists in the Colab environment.
    file_name = '2020_al_data_kaggle_upload_new_old_syllabi.csv' # This name is derived from the initial upload cell
    try:
        df = pd.read_csv(file_name)
        print(f"Successfully reloaded '{file_name}' into 'df'.")
    except FileNotFoundError:
        print(f"Error: '{file_name}' not found. Please re-run the initial data upload cell (Cell AaeH4shTX6Y9) first.")
        raise # Re-raise to prevent further execution if df can't be loaded
    except Exception as e:
        print(f"An error occurred while reloading df: {e}")
        raise

# Prepare df_cleaned by converting 'Zscore' to numeric, coercing errors to NaN
# This step was implicitly performed or assumed for the original filtering in cell 38529b01
df_cleaned = df.copy()
df_cleaned['Zscore'] = pd.to_numeric(df_cleaned['Zscore'], errors='coerce')

# Redefine biological_science_high_zscore_students from df_cleaned
biological_science_high_zscore_students = df_cleaned[
    (df_cleaned['stream'] == 'BIOLOGICAL SCIENCE') &
    (df_cleaned['Zscore'] > 0.4)
].copy() # Use .copy() to avoid SettingWithCopyWarning later

initial_rows = len(biological_science_high_zscore_students)
biological_science_high_zscore_students_cleaned = biological_science_high_zscore_students.dropna()
rows_after_cleaning = len(biological_science_high_zscore_students_cleaned)

print(f"Original number of rows for biological_science_high_zscore_students: {initial_rows}")
print(f"Number of rows after dropping nulls: {rows_after_cleaning}")
print(f"Number of rows dropped: {initial_rows - rows_after_cleaning}")

display(biological_science_high_zscore_students_cleaned.head())

DataFrame 'df' not found, attempting to reload from original CSV.
Error: '2020_al_data_kaggle_upload_new_old_syllabi.csv' not found. Please re-run the initial data upload cell (Cell AaeH4shTX6Y9) first.

FileNotFoundError: [Errno 2] No such file or directory: '2020_al_data_kaggle_upload_new_old_syllabi.csv'

### Data Cleaning and Transformation

This step addresses the identified issues:
1.  **Numeric Conversion for Zscore**: Converts the `Zscore` column to a numeric type, coercing any non-numeric values to `NaN`.
2.  **Standardize Categorical Columns**: Converts relevant categorical columns to lowercase to handle inconsistent capitalization.
3.  **Handle Missing Values**: Removes rows containing any `NaN` values, ensuring a clean dataset for analysis.

In [ ]:
# Make a copy to avoid modifying the original 'df' if not intended for broader changes
df_transformed = df.copy()

# 1. Convert 'Zscore' to numeric, coercing errors to NaN
df_transformed['Zscore'] = pd.to_numeric(df_transformed['Zscore'], errors='coerce')

# 2. Identify categorical columns that might have capitalization issues and convert to lowercase
# Based on df.dtypes and common categorical columns in this dataset
string_cols_to_lower = ['stream', 'sub1', 'sub1_r', 'sub2', 'sub2_r', 'sub3', 'sub3_r', 'cgt_r', 'ge_r', 'syllabus', 'gender']

for col in string_cols_to_lower:
    if col in df_transformed.columns:
        df_transformed[col] = df_transformed[col].astype(str).str.lower()

# Redefine biological_science_high_zscore_students after initial transformations
biological_science_high_zscore_students_transformed = df_transformed[
    (df_transformed['stream'] == 'biological science') &
    (df_transformed['Zscore'] > 0.4)
].copy() # Use .copy() to avoid SettingWithCopyWarning

# 3. Drop rows with any missing values
initial_rows_transformed = len(biological_science_high_zscore_students_transformed)
biological_science_high_zscore_students_final = biological_science_high_zscore_students_transformed.dropna()
rows_after_cleaning_final = len(biological_science_high_zscore_students_final)

print(f"Original number of rows for biological_science_high_zscore_students after initial transform: {initial_rows_transformed}")
print(f"Number of rows after dropping nulls: {rows_after_cleaning_final}")
print(f"Number of rows dropped due to nulls: {initial_rows_transformed - rows_after_cleaning_final}")

display(biological_science_high_zscore_students_final.head())
print("\nInfo of the final DataFrame after transformations:")
biosci_df_info = io.StringIO()
biological_science_high_zscore_students_final.info(buf=biosci_df_info)
print(biosci_df_info.getvalue())

Original number of rows for biological_science_high_zscore_students after initial transform: 14163
Number of rows after dropping nulls: 14163
Number of rows dropped due to nulls: 0

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender
221,221,biological science,0.8301,1401 (NEW),7642 (NEW),2020,physics,s,chemistry,c,biology,c,066,a,new,16,July,2001,male
268,268,biological science,1.3942,761 (NEW),3551 (NEW),2020,physics,b,chemistry,b,biology,c,068,a,new,21,October,2001,male
293,293,biological science,2.4107,57 (NEW),211 (NEW),2020,physics,a,chemistry,a,biology,b,060,b,new,26,July,2001,male
362,362,biological science,1.1235,1050 (NEW),5268 (NEW),2020,physics,c,chemistry,b,biology,c,070,a,new,26,January,2001,male
367,367,biological science,1.1875,971 (NEW),4809 (NEW),2020,physics,c,chemistry,c,biology,a,absent,absent,new,9,October,2000,male

Info of the final DataFrame after transformations:
<class 'pandas.core.frame.DataFrame'>
Index: 14163 entries, 221 to 337385
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          14163 non-null  int64
 1   stream         14163 non-null  object
 2   Zscore         14163 non-null  float64
 3   district_rank  14163 non-null  object
 4   island_rank    14163 non-null  object
 5   al_year        14163 non-null  int64
 6   sub1           14163 non-null  object
 7   sub1_r         14163 non-null  object
 8   sub2           14163 non-null  object
 9   sub2_r         14163 non-null  object
 10  sub3           14163 non-null  object
 11  sub3_r         14163 non-null  object
 12  cgt_r          14163 non-null  object
 13  ge_r           14163 non-null  object
 14  syllabus       14163 non-null  object
 15  birth_day      14163 non-null  object
 16  birth_month    14163 non-null  object
 17  birth_year     14163 non-null  object
 18  gender         14163 non-null  object
dtypes: float64(1), int64(2), object(16)
memory usage: 2.2+ MB

### Students with Z-score > 0.4 in BIOLOGICAL SCIENCE Stream (New Syllabus Only)

In [ ]:
# Filter for students on the 'new' syllabus
biological_science_new_syllabus = biological_science_high_zscore_students[
    biological_science_high_zscore_students['syllabus'] == 'new'
]

# Display the results
print(f"Number of students in 'BIOLOGICAL SCIENCE' stream with Z-score > 0.4 (New Syllabus): {len(biological_science_new_syllabus)}")
display(biological_science_new_syllabus.head())

Number of students in 'BIOLOGICAL SCIENCE' stream with Z-score > 0.4 (New Syllabus): 11715

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender
221,221,BIOLOGICAL SCIENCE,0.8301,1401 (NEW),7642 (NEW),2020,PHYSICS,S,CHEMISTRY,C,BIOLOGY,C,066,A,new,16,July,2001,male
268,268,BIOLOGICAL SCIENCE,1.3942,761 (NEW),3551 (NEW),2020,PHYSICS,B,CHEMISTRY,B,BIOLOGY,C,068,A,new,21,October,2001,male
293,293,BIOLOGICAL SCIENCE,2.4107,57 (NEW),211 (NEW),2020,PHYSICS,A,CHEMISTRY,A,BIOLOGY,B,060,B,new,26,July,2001,male
362,362,BIOLOGICAL SCIENCE,1.1235,1050 (NEW),5268 (NEW),2020,PHYSICS,C,CHEMISTRY,B,BIOLOGY,C,070,A,new,26,January,2001,male
367,367,BIOLOGICAL SCIENCE,1.1875,971 (NEW),4809 (NEW),2020,PHYSICS,C,CHEMISTRY,C,BIOLOGY,A,Absent,Absent,new,9,October,2000,male

### Save New Syllabus Data to CSV and Download

In [ ]:
# Define the output CSV file name for new syllabus students
output_csv_file_new_syllabus = 'biological_science_high_zscore_new_syllabus_students.csv'

# Filter for students on the 'new' syllabus, using the final cleaned DataFrame
biological_science_new_syllabus = biological_science_high_zscore_students_final[
    biological_science_high_zscore_students_final['syllabus'] == 'new'
]

# Save the filtered DataFrame to a CSV file
biological_science_new_syllabus.to_csv(output_csv_file_new_syllabus, index=False)

print(f"Data saved to {output_csv_file_new_syllabus}")

# Provide a download link
files.download(output_csv_file_new_syllabus)

Data saved to biological_science_high_zscore_new_syllabus_students.csv

### Removing Duplicate Rows

This step identifies and removes any duplicate rows from the `biological_science_high_zscore_students_final` DataFrame to ensure each entry is unique. This is important for accurate analysis and to prevent skewed statistics.

In [ ]:
# Store the initial number of rows before dropping duplicates
initial_rows_before_deduplication = len(biological_science_high_zscore_students_final)

# Remove duplicate rows from the DataFrame
# By default, keep='first' is used, meaning the first occurrence is kept and subsequent duplicates are dropped.
biological_science_high_zscore_students_deduplicated = biological_science_high_zscore_students_final.drop_duplicates()

# Get the number of rows after dropping duplicates
rows_after_deduplication = len(biological_science_high_zscore_students_deduplicated)

print(f"Number of rows before removing duplicates: {initial_rows_before_deduplication}")
print(f"Number of rows after removing duplicates: {rows_after_deduplication}")
print(f"Number of duplicate rows removed: {initial_rows_before_deduplication - rows_after_deduplication}")

display(biological_science_high_zscore_students_deduplicated.head())

Number of rows before removing duplicates: 14163
Number of rows after removing duplicates: 14163
Number of duplicate rows removed: 0

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender
221,221,biological science,0.8301,1401 (NEW),7642 (NEW),2020,physics,s,chemistry,c,biology,c,066,a,new,16,July,2001,male
268,268,biological science,1.3942,761 (NEW),3551 (NEW),2020,physics,b,chemistry,b,biology,c,068,a,new,21,October,2001,male
293,293,biological science,2.4107,57 (NEW),211 (NEW),2020,physics,a,chemistry,a,biology,b,060,b,new,26,July,2001,male
362,362,biological science,1.1235,1050 (NEW),5268 (NEW),2020,physics,c,chemistry,b,biology,c,070,a,new,26,January,2001,male
367,367,biological science,1.1875,971 (NEW),4809 (NEW),2020,physics,c,chemistry,c,biology,a,absent,absent,new,9,October,2000,male

In [3]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

# Automatically get the uploaded filename
file_name = list(uploaded.keys())[0]

print("Uploaded file:", file_name)

olap_data = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("Shape:", olap_data.shape)

display(olap_data.head())

Saving biological_science_high_zscore_new_syllabus_students (3).csv to biological_science_high_zscore_new_syllabus_students (3).csv
Uploaded file: biological_science_high_zscore_new_syllabus_students (3).csv
Dataset loaded successfully!
Shape: (11715, 19)

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender
0,221,BIOLOGICAL SCIENCE,0.8301,1401 (NEW),7642 (NEW),2020,PHYSICS,S,CHEMISTRY,C,BIOLOGY,C,066,A,new,16,July,2001,male
1,268,BIOLOGICAL SCIENCE,1.3942,761 (NEW),3551 (NEW),2020,PHYSICS,B,CHEMISTRY,B,BIOLOGY,C,068,A,new,21,October,2001,male
2,293,BIOLOGICAL SCIENCE,2.4107,57 (NEW),211 (NEW),2020,PHYSICS,A,CHEMISTRY,A,BIOLOGY,B,060,B,new,26,July,2001,male
3,362,BIOLOGICAL SCIENCE,1.1235,1050 (NEW),5268 (NEW),2020,PHYSICS,C,CHEMISTRY,B,BIOLOGY,C,070,A,new,26,January,2001,male
4,367,BIOLOGICAL SCIENCE,1.1875,971 (NEW),4809 (NEW),2020,PHYSICS,C,CHEMISTRY,C,BIOLOGY,A,Absent,Absent,new,9,October,2000,male

In [5]:
from google.colab import files
import pandas as pd

# This will open the file picker
uploaded = files.upload()

# Automatically use whatever CSV you select
file_name = next(iter(uploaded))

print("Uploaded:", file_name)

olap_data = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("Shape:", olap_data.shape)

display(olap_data.head())

Saving biological_science_high_zscore_new_syllabus_students (3).csv to biological_science_high_zscore_new_syllabus_students (3) (1).csv
Uploaded: biological_science_high_zscore_new_syllabus_students (3) (1).csv
Dataset loaded successfully!
Shape: (11715, 19)

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender
0,221,BIOLOGICAL SCIENCE,0.8301,1401 (NEW),7642 (NEW),2020,PHYSICS,S,CHEMISTRY,C,BIOLOGY,C,066,A,new,16,July,2001,male
1,268,BIOLOGICAL SCIENCE,1.3942,761 (NEW),3551 (NEW),2020,PHYSICS,B,CHEMISTRY,B,BIOLOGY,C,068,A,new,21,October,2001,male
2,293,BIOLOGICAL SCIENCE,2.4107,57 (NEW),211 (NEW),2020,PHYSICS,A,CHEMISTRY,A,BIOLOGY,B,060,B,new,26,July,2001,male
3,362,BIOLOGICAL SCIENCE,1.1235,1050 (NEW),5268 (NEW),2020,PHYSICS,C,CHEMISTRY,B,BIOLOGY,C,070,A,new,26,January,2001,male
4,367,BIOLOGICAL SCIENCE,1.1875,971 (NEW),4809 (NEW),2020,PHYSICS,C,CHEMISTRY,C,BIOLOGY,A,Absent,Absent,new,9,October,2000,male

In [6]:
# Prepare numeric measures for OLAP

olap_data['Zscore'] = pd.to_numeric(
    olap_data['Zscore'],
    errors='coerce'
)

olap_data['district_rank_num'] = (
    olap_data['district_rank']
    .astype(str)
    .str.extract(r'(\d+)')[0]
)

olap_data['district_rank_num'] = pd.to_numeric(
    olap_data['district_rank_num'],
    errors='coerce'
)

olap_data['island_rank_num'] = (
    olap_data['island_rank']
    .astype(str)
    .str.extract(r'(\d+)')[0]
)

olap_data['island_rank_num'] = pd.to_numeric(
    olap_data['island_rank_num'],
    errors='coerce'
)

olap_data['cgt_score'] = pd.to_numeric(
    olap_data['cgt_r'],
    errors='coerce'
)

print("OLAP measures prepared successfully!")

display(
    olap_data[
        ['Zscore', 'district_rank_num', 'island_rank_num', 'cgt_score']
    ].head()
)

OLAP measures prepared successfully!

   Zscore  district_rank_num  island_rank_num  cgt_score
0  0.8301               1401             7642       66.0
1  1.3942                761             3551       68.0
2  2.4107                 57              211       60.0
3  1.1235               1050             5268       70.0
4  1.1875                971             4809        NaN

In [7]:
# ============================================================
# DIMENSION TABLE 1: STUDENT
# ============================================================

dim_student = olap_data[
    [
        'index',
        'gender',
        'birth_day',
        'birth_month',
        'birth_year'
    ]
].drop_duplicates().reset_index(drop=True)

# Create surrogate key
dim_student.insert(
    0,
    'student_key',
    range(1, len(dim_student) + 1)
)

# Rename original index column
dim_student.rename(
    columns={'index': 'source_index'},
    inplace=True
)

print("DIM_STUDENT created successfully!")
print("Shape:", dim_student.shape)

display(dim_student.head())

DIM_STUDENT created successfully!
Shape: (11715, 6)

   student_key  source_index gender birth_day birth_month birth_year
0            1           221   male        16        July       2001
1            2           268   male        21     October       2001
2            3           293   male        26        July       2001
3            4           362   male        26     January       2001
4            5           367   male         9     October       2000

In [8]:
# ============================================================
# DIMENSION TABLE 2: EXAM
# ============================================================

dim_exam = olap_data[
    [
        'al_year',
        'stream',
        'syllabus'
    ]
].drop_duplicates().reset_index(drop=True)

# Create surrogate key
dim_exam.insert(
    0,
    'exam_key',
    range(1, len(dim_exam) + 1)
)

print("DIM_EXAM created successfully!")
print("Shape:", dim_exam.shape)

display(dim_exam)

DIM_EXAM created successfully!
Shape: (1, 4)

   exam_key  al_year              stream syllabus
0         1     2020  BIOLOGICAL SCIENCE      new

In [9]:
# ============================================================
# DIMENSION TABLE 3: SUBJECT
# ============================================================

dim_subject = olap_data[
    [
        'sub1',
        'sub2',
        'sub3'
    ]
].drop_duplicates().reset_index(drop=True)

# Create surrogate key
dim_subject.insert(
    0,
    'subject_key',
    range(1, len(dim_subject) + 1)
)

# Rename columns
dim_subject.rename(
    columns={
        'sub1': 'subject_1',
        'sub2': 'subject_2',
        'sub3': 'subject_3'
    },
    inplace=True
)

print("DIM_SUBJECT created successfully!")
print("Shape:", dim_subject.shape)

display(dim_subject)

DIM_SUBJECT created successfully!
Shape: (2, 4)

   subject_key  subject_1             subject_2 subject_3
0            1    PHYSICS             CHEMISTRY   BIOLOGY
1            2  CHEMISTRY  AGRICULTURAL SCIENCE   BIOLOGY

In [10]:
# ============================================================
# FACT TABLE: FACT_RESULTS
# ============================================================

fact = olap_data.copy()

# 1. Connect DIM_STUDENT
fact = fact.merge(
    dim_student[['student_key', 'source_index']],
    left_on='index',
    right_on='source_index',
    how='left'
)

# 2. Connect DIM_EXAM
fact = fact.merge(
    dim_exam,
    on=['al_year', 'stream', 'syllabus'],
    how='left'
)

# 3. Prepare DIM_SUBJECT for connection
subject_lookup = dim_subject.rename(
    columns={
        'subject_1': 'sub1',
        'subject_2': 'sub2',
        'subject_3': 'sub3'
    }
)

# Connect DIM_SUBJECT
fact = fact.merge(
    subject_lookup,
    on=['sub1', 'sub2', 'sub3'],
    how='left'
)

# 4. Create final FACT table
fact_results = fact[
    [
        'student_key',
        'exam_key',
        'subject_key',
        'Zscore',
        'district_rank_num',
        'island_rank_num',
        'cgt_score',
        'sub1_r',
        'sub2_r',
        'sub3_r',
        'ge_r'
    ]
].copy()

# Create Fact Table primary key
fact_results.insert(
    0,
    'result_key',
    range(1, len(fact_results) + 1)
)

# Rename columns
fact_results.rename(
    columns={
        'Zscore': 'zscore',
        'district_rank_num': 'district_rank',
        'island_rank_num': 'island_rank',
        'sub1_r': 'subject_1_grade',
        'sub2_r': 'subject_2_grade',
        'sub3_r': 'subject_3_grade',
        'ge_r': 'general_english_grade'
    },
    inplace=True
)

print("FACT_RESULTS created successfully!")
print("Shape:", fact_results.shape)

display(fact_results.head())

FACT_RESULTS created successfully!
Shape: (11715, 12)

,result_key,student_key,exam_key,subject_key,zscore,district_rank,island_rank,cgt_score,subject_1_grade,subject_2_grade,subject_3_grade,general_english_grade
0,1,1,1,1,0.8301,1401,7642,66.0,S,C,C,A
1,2,2,1,1,1.3942,761,3551,68.0,B,B,C,A
2,3,3,1,1,2.4107,57,211,60.0,A,A,B,B
3,4,4,1,1,1.1235,1050,5268,70.0,C,B,C,A
4,5,5,1,1,1.1875,971,4809,NaN,C,C,A,Absent

In [11]:
# ============================================================
# FINAL STAR SCHEMA VALIDATION
# ============================================================

print("=" * 60)
print("STAR SCHEMA VALIDATION")
print("=" * 60)

print("\nDimension Tables")
print("DIM_STUDENT :", dim_student.shape)
print("DIM_EXAM    :", dim_exam.shape)
print("DIM_SUBJECT :", dim_subject.shape)

print("\nFact Table")
print("FACT_RESULTS:", fact_results.shape)

# Check missing foreign keys
print("\nMissing Foreign Keys")

print(
    "Missing student_key:",
    fact_results['student_key'].isna().sum()
)

print(
    "Missing exam_key:",
    fact_results['exam_key'].isna().sum()
)

print(
    "Missing subject_key:",
    fact_results['subject_key'].isna().sum()
)

# Preview tables
print("\nDIM_STUDENT")
display(dim_student.head())

print("\nDIM_EXAM")
display(dim_exam.head())

print("\nDIM_SUBJECT")
display(dim_subject.head())

print("\nFACT_RESULTS")
display(fact_results.head())

============================================================
STAR SCHEMA VALIDATION
============================================================

Dimension Tables
DIM_STUDENT : (11715, 6)
DIM_EXAM    : (1, 4)
DIM_SUBJECT : (2, 4)

Fact Table
FACT_RESULTS: (11715, 12)

Missing Foreign Keys
Missing student_key: 0
Missing exam_key: 0
Missing subject_key: 0

DIM_STUDENT

   student_key  source_index gender birth_day birth_month birth_year
0            1           221   male        16        July       2001
1            2           268   male        21     October       2001
2            3           293   male        26        July       2001
3            4           362   male        26     January       2001
4            5           367   male         9     October       2000

DIM_EXAM

   exam_key  al_year              stream syllabus
0         1     2020  BIOLOGICAL SCIENCE      new

DIM_SUBJECT

   subject_key  subject_1             subject_2 subject_3
0            1    PHYSICS             CHEMISTRY   BIOLOGY
1            2  CHEMISTRY  AGRICULTURAL SCIENCE   BIOLOGY

FACT_RESULTS

,result_key,student_key,exam_key,subject_key,zscore,district_rank,island_rank,cgt_score,subject_1_grade,subject_2_grade,subject_3_grade,general_english_grade
0,1,1,1,1,0.8301,1401,7642,66.0,S,C,C,A
1,2,2,1,1,1.3942,761,3551,68.0,B,B,C,A
2,3,3,1,1,2.4107,57,211,60.0,A,A,B,B
3,4,4,1,1,1.1235,1050,5268,70.0,C,B,C,A
4,5,5,1,1,1.1875,971,4809,NaN,C,C,A,Absent

In [12]:
# ============================================================
# 5. POPULATE OLAP CUBE
# ============================================================

olap_cube_data = (
    fact_results
    .merge(dim_student, on='student_key', how='left')
    .merge(dim_exam, on='exam_key', how='left')
    .merge(dim_subject, on='subject_key', how='left')
)

print("OLAP cube data populated successfully!")
print("Shape:", olap_cube_data.shape)

display(olap_cube_data.head())

OLAP cube data populated successfully!
Shape: (11715, 23)

,result_key,student_key,exam_key,subject_key,zscore,district_rank,island_rank,cgt_score,subject_1_grade,subject_2_grade,...,gender,birth_day,birth_month,birth_year,al_year,stream,syllabus,subject_1,subject_2,subject_3
0,1,1,1,1,0.8301,1401,7642,66.0,S,C,...,male,16,July,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
1,2,2,1,1,1.3942,761,3551,68.0,B,B,...,male,21,October,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
2,3,3,1,1,2.4107,57,211,60.0,A,A,...,male,26,July,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
3,4,4,1,1,1.1235,1050,5268,70.0,C,B,...,male,26,January,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
4,5,5,1,1,1.1875,971,4809,NaN,C,C,...,male,9,October,2000,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY

In [13]:
# ============================================================
# 6. VALIDATE AND TEST OLAP CUBE
# ============================================================

print("=" * 60)
print("OLAP CUBE VALIDATION")
print("=" * 60)

# 1. Check cube size
print("\nCube Shape:")
print(olap_cube_data.shape)

# 2. Check missing dimension keys
print("\nMissing Keys:")
print("student_key :", olap_cube_data['student_key'].isna().sum())
print("exam_key    :", olap_cube_data['exam_key'].isna().sum())
print("subject_key :", olap_cube_data['subject_key'].isna().sum())

# 3. Check important measures
print("\nMeasure Validation:")
print("Missing Z-score :", olap_cube_data['zscore'].isna().sum())
print("Missing CGT     :", olap_cube_data['cgt_score'].isna().sum())

# 4. Test aggregation
test_cube = olap_cube_data.groupby('gender').agg(
    student_count=('student_key', 'count'),
    average_zscore=('zscore', 'mean'),
    min_zscore=('zscore', 'min'),
    max_zscore=('zscore', 'max')
).reset_index()

print("\nTest Cube - Performance by Gender:")
display(test_cube)

# 5. Check total records
print("\nRecord Validation:")
print("Fact table records :", len(fact_results))
print("Cube records       :", len(olap_cube_data))

if len(fact_results) == len(olap_cube_data):
    print("Record count validation: PASSED")
else:
    print("Record count validation: FAILED")

============================================================
OLAP CUBE VALIDATION
============================================================

Cube Shape:
(11715, 23)

Missing Keys:
student_key : 0
exam_key    : 0
subject_key : 0

Measure Validation:
Missing Z-score : 0
Missing CGT     : 2817

Test Cube - Performance by Gender:

   gender  student_count  average_zscore  min_zscore  max_zscore
0  female           8464        1.089580      0.4001      3.0144
1    male           3248        1.225174      0.4005      3.3182

Record Validation:
Fact table records : 11715
Cube records       : 11715
Record count validation: PASSED

In [14]:
# ============================================================
# 7.1 SLICE OPERATION
# ============================================================

# Select only female students from the OLAP cube
slice_cube = olap_cube_data[
    olap_cube_data['gender'] == 'female'
]

print("SLICE: Female Students")
print("Number of records:", len(slice_cube))

display(slice_cube.head())

SLICE: Female Students
Number of records: 8464

,result_key,student_key,exam_key,subject_key,zscore,district_rank,island_rank,cgt_score,subject_1_grade,subject_2_grade,...,gender,birth_day,birth_month,birth_year,al_year,stream,syllabus,subject_1,subject_2,subject_3
7,8,8,1,1,1.5471,610,2734,64.0,C,A,...,female,11,May,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
8,9,9,1,1,1.1755,990,4912,62.0,C,B,...,female,6,March,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
9,10,10,1,1,0.9469,1266,6634,68.0,S,B,...,female,15,July,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
10,11,11,1,1,1.0414,1146,5877,68.0,C,B,...,female,10,December,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
11,12,12,1,1,0.5813,1710,10109,64.0,C,C,...,female,19,June,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY

In [15]:
# ============================================================
# 7. PERFORM OLAP OPERATIONS
# ============================================================

# ------------------------------------------------------------
# 7.1 SLICE
# Select only female students
# ------------------------------------------------------------

slice_cube = olap_cube_data[
    olap_cube_data['gender'] == 'female'
]

print("=" * 60)
print("7.1 SLICE - Female Students")
print("=" * 60)

print("Number of records:", len(slice_cube))
display(slice_cube.head())


# ------------------------------------------------------------
# 7.2 DICE
# Select female students born in selected years
# and following Physics-Chemistry-Biology combination
# ------------------------------------------------------------

dice_cube = olap_cube_data[
    (olap_cube_data['gender'] == 'female') &
    (olap_cube_data['birth_year'].isin([2000, 2001, 2002])) &
    (olap_cube_data['subject_1'] == 'PHYSICS')
]

print("\n" + "=" * 60)
print("7.2 DICE - Female + Birth Year + Physics")
print("=" * 60)

print("Number of records:", len(dice_cube))
display(dice_cube.head())


# ------------------------------------------------------------
# 7.3 ROLL-UP
# Aggregate detailed student records to birth year level
# ------------------------------------------------------------

rollup_cube = olap_cube_data.groupby(
    'birth_year'
).agg(
    student_count=('student_key', 'count'),
    average_zscore=('zscore', 'mean'),
    average_cgt=('cgt_score', 'mean')
).reset_index()

print("\n" + "=" * 60)
print("7.3 ROLL-UP - Performance by Birth Year")
print("=" * 60)

display(rollup_cube)


# ------------------------------------------------------------
# 7.4 DRILL-DOWN
# Move from Birth Year to Birth Month
# ------------------------------------------------------------

drilldown_cube = olap_cube_data.groupby(
    ['birth_year', 'birth_month']
).agg(
    student_count=('student_key', 'count'),
    average_zscore=('zscore', 'mean')
).reset_index()

print("\n" + "=" * 60)
print("7.4 DRILL-DOWN - Birth Year -> Birth Month")
print("=" * 60)

display(drilldown_cube.head(20))


# ------------------------------------------------------------
# 7.5 PIVOT
# Compare average Z-score by gender and subject combination
# ------------------------------------------------------------

pivot_cube = pd.pivot_table(
    olap_cube_data,
    values='zscore',
    index='gender',
    columns='subject_1',
    aggfunc='mean'
)

print("\n" + "=" * 60)
print("7.5 PIVOT - Average Z-score by Gender and Subject")
print("=" * 60)

display(pivot_cube)

============================================================
7.1 SLICE - Female Students
============================================================
Number of records: 8464

,result_key,student_key,exam_key,subject_key,zscore,district_rank,island_rank,cgt_score,subject_1_grade,subject_2_grade,...,gender,birth_day,birth_month,birth_year,al_year,stream,syllabus,subject_1,subject_2,subject_3
7,8,8,1,1,1.5471,610,2734,64.0,C,A,...,female,11,May,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
8,9,9,1,1,1.1755,990,4912,62.0,C,B,...,female,6,March,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
9,10,10,1,1,0.9469,1266,6634,68.0,S,B,...,female,15,July,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
10,11,11,1,1,1.0414,1146,5877,68.0,C,B,...,female,10,December,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY
11,12,12,1,1,0.5813,1710,10109,64.0,C,C,...,female,19,June,2001,2020,BIOLOGICAL SCIENCE,new,PHYSICS,CHEMISTRY,BIOLOGY

============================================================
7.2 DICE - Female + Birth Year + Physics
============================================================
Number of records: 0

Empty DataFrame
Columns: [result_key, student_key, exam_key, subject_key, zscore, district_rank, island_rank, cgt_score, subject_1_grade, subject_2_grade, subject_3_grade, general_english_grade, source_index, gender, birth_day, birth_month, birth_year, al_year, stream, syllabus, subject_1, subject_2, subject_3]
Index: []

[0 rows x 23 columns]

============================================================
7.3 ROLL-UP - Performance by Birth Year
============================================================

          birth_year  student_count  average_zscore  average_cgt
0               1995              1        0.444300          NaN
1               1997              3        0.518000    56.000000
2               1998             13        1.272985    56.000000
3               1999             82        1.045710    60.688525
4               2000           5300        1.123560    61.618564
5               2001           5766        1.128079    62.853160
6               2002            541        1.164290    63.642458
7               2003              5        1.181420    59.600000
8  Invalid day error              1        2.117800          NaN
9  Invalid nic error              3        1.301800    53.333333

============================================================
7.4 DRILL-DOWN - Birth Year -> Birth Month
============================================================

   birth_year birth_month  student_count  average_zscore
0        1995    November              1        0.444300
1        1997    February              3        0.518000
2        1998       April              2        1.248500
3        1998      August              1        1.529600
4        1998        June              3        1.500600
5        1998       March              3        0.911433
6        1998         May              1        1.872600
7        1998    November              1        0.652500
8        1998   September              2        1.380500
9        1999       April              8        0.903537
10       1999      August              5        0.819780
11       1999    December              8        1.033675
12       1999    February              4        1.174650
13       1999     January              2        0.831550
14       1999        July              6        1.024867
15       1999        June              4        0.571925
16       1999       March              4        0.966850
17       1999         May             10        1.203280
18       1999    November              9        1.192644
19       1999     October             10        0.912500

============================================================
7.5 PIVOT - Average Z-score by Gender and Subject
============================================================

subject_1  CHEMISTRY   PHYSICS
gender
female      0.803968  1.105580
male        0.876421  1.237744